"""add KRA PIN fields to users and clients

Revision ID: 2ba18a6dbed7
Revises: e970a0152146
Create Date: 2026-06-30 09:22:41.849513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba18a6dbed7'
down_revision = 'e970a0152146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kra_pin', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kra_pin', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('kra_pin')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('kra_pin')

    # ### end Alembic commands ###
