"""add recurring invoices table

Revision ID: 41de4cc2ae80
Revises: 95f2c5056489
Create Date: 2026-06-30 22:34:02.675585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41de4cc2ae80'
down_revision = '95f2c5056489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('items_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('next_run_date', sa.Date(), nullable=False),
    sa.Column('last_run_date', sa.Date(), nullable=True),
    sa.Column('invoices_generated', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_invoices')
    # ### end Alembic commands ###
