"""add invoice template preference to user

Revision ID: 7c360c71cdf5
Revises: 2ba18a6dbed7
Create Date: 2026-06-30 09:36:33.981401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c360c71cdf5'
down_revision = '2ba18a6dbed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_template', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('invoice_template')

    # ### end Alembic commands ###
