"""add subscription fields to users

Revision ID: aeec6d2a5e10
Revises: 41de4cc2ae80
Create Date: 2026-07-01 12:20:58.099794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeec6d2a5e10'
down_revision = '41de4cc2ae80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('plan_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('paystack_customer_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paystack_subscription_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('plan_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invoice_count_this_month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invoice_count_reset_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('invoice_count_reset_date')
        batch_op.drop_column('invoice_count_this_month')
        batch_op.drop_column('plan_expires_at')
        batch_op.drop_column('paystack_subscription_code')
        batch_op.drop_column('paystack_customer_code')
        batch_op.drop_column('plan_status')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
