"""add portal token to invoices

Revision ID: e970a0152146
Revises: d86faca6e42b
Create Date: 2026-06-26 23:05:21.541601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e970a0152146'
down_revision = 'd86faca6e42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portal_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['portal_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('portal_token')

    # ### end Alembic commands ###
